function filter = cheby2filt
%CHEBY2FILT Returns a discrete-time filter object.

%
% M-File generated by MATLAB(R) 7.10 and the Signal Processing Toolbox 6.13.
%
% Generated on: 26-Jun-2012 15:02:03
%

% Chebyshev Type II Bandpass filter designed using FDESIGN.BANDPASS.

% All frequency values are in Hz.
Fs = 5000;  % Sampling Frequency

Fstop1 = 0.1;         % First Stopband Frequency
Fpass1 = 0.5;         % First Passband Frequency
Fpass2 = 4;           % Second Passband Frequency
Fstop2 = 10;          % Second Stopband Frequency
Astop1 = .1;          % First Stopband Attenuation (dB)
Apass  = 500;           % Passband Ripple (dB)
Astop2 = 820;          % Second Stopband Attenuation (dB)
match  = 'passband';  % Band to match exactly

% Construct an FDESIGN object and call its CHEBY2 method.
h  = fdesign.bandpass(Fstop1, Fpass1, Fpass2, Fstop2, Astop1, Apass, ...
                      Astop2, Fs);
filter = design(h, 'cheby2', 'MatchExactly', match);

% [EOF]
